################################################################################
# Environment script generated by ilcsoft-install on Fri Aug  5 12:56:30 2016
# for the installation located at [ /afs/desy.de/project/ilcsoft/sw/x86_64_gcc44_sl6 ]
################################################################################

SET( ILC_HOME "/afs/desy.de/project/ilcsoft/sw/x86_64_gcc44_sl6" CACHE PATH "Path to ILC Software" FORCE)
MARK_AS_ADVANCED( ILC_HOME )

SET( CMAKE_PREFIX_PATH 
	${ILC_HOME}/mysql/5.0.45;
	${ILC_HOME}/ilcutil/v01-03;
	${ILC_HOME}/CondDBMySQL/CondDBMySQL_ILC-0-9-6;
	${ILC_HOME}/CED/v01-09-01;
	${ILC_HOME}/FastJet/3.2.0;
	${ILC_HOME}/xercesc/3.1.2;
	${ILC_HOME}/geant4/10.01;
	${ILC_HOME}/root/5.34.30;
	${ILC_HOME}/CLHEP/2.1.4.1;
	${ILC_HOME}/gsl/2.1;
	${ILC_HOME}/QT/4.7.4;
CACHE PATH "CMAKE_PREFIX_PATH" FORCE )

#
#

option(USE_CXX11 "Use cxx11" False)
option(Boost_NO_BOOST_CMAKE "dont use cmake find module for boost" OFF)
